# Generated by Django 2.1.1 on 2021-02-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fotoPortada',
            field=models.ImageField(blank=True, upload_to='portadas/'),
        ),
    ]
