# Generated by Django 2.1.1 on 2021-02-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries', '0002_vehiculo_fotoportada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('OLD', 'Usado'), ('NEW', 'Nuevo')], max_length=3),
        ),
    ]
