# Generated by Django 2.2 on 2021-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries', '0003_auto_20210215_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='version',
            field=models.CharField(default='0.0', max_length=50),
            preserve_default=False,
        ),
    ]
